import { moduleRegistry } from './registry';
import type { FrontendModuleDefinition } from './types';
import { overviewModule } from '../../../modules/overview/frontend';
import { serversModule } from '../../../modules/servers/frontend';
import { problemsModule } from '../../../modules/problems/frontend';

// Module definitions for the 21 Product Specification modules
const moduleDefinitions: FrontendModuleDefinition[] = [
  overviewModule,
  serversModule,
  problemsModule,
  {
    id: 'availability',
    name: 'Availability',
    version: '0.1.0',
    description: 'Infrastructure and SLA availability reporting and downtime timelines',
    enabled: true,
    route: '/availability',
    navItem: { label: 'Availability', path: '/availability', order: 4 },
    permissions: ['module.availability.view'],
  },
  {
    id: 'host360',
    name: 'Host 360',
    version: '0.1.0',
    description: 'Comprehensive 360-degree host telemetry, metrics, and event overlays',
    enabled: true,
    route: '/host360',
    navItem: { label: 'Host 360', path: '/host360', order: 5 },
    permissions: ['module.host360.view'],
  },
  {
    id: 'top_n',
    name: 'Top N',
    version: '0.1.0',
    description: 'Ranked resource utilization (CPU, memory, disk, network, latency, downtime)',
    enabled: true,
    route: '/top-n',
    navItem: { label: 'Top N', path: '/top-n', order: 6 },
    permissions: ['module.top_n.view'],
  },
  {
    id: 'graph_explorer',
    name: 'Graph Explorer',
    version: '0.1.0',
    description: 'Interactive multi-series metric visualization and comparison',
    enabled: true,
    route: '/graphs',
    navItem: { label: 'Graph Explorer', path: '/graphs', order: 7 },
    permissions: ['module.graph_explorer.view'],
  },
  {
    id: 'global_search',
    name: 'Global Search',
    version: '0.1.0',
    description: 'Cross-platform unified search across hosts, items, problems, and services',
    enabled: true,
    route: '/search',
    navItem: { label: 'Global Search', path: '/search', order: 8 },
    permissions: ['module.global_search.view'],
  },
  {
    id: 'network',
    name: 'Network Operations',
    version: '0.1.0',
    description: 'Network switch, router, interface, port utilization, and topology observability',
    enabled: true,
    route: '/network',
    navItem: { label: 'Network', path: '/network', order: 9 },
    permissions: ['module.network.view'],
  },
  {
    id: 'database',
    name: 'Database Operations',
    version: '0.1.0',
    description: 'Database performance metrics for PostgreSQL, MySQL, Oracle, and SQL Server',
    enabled: true,
    route: '/database',
    navItem: { label: 'Database', path: '/database', order: 10 },
    permissions: ['module.database.view'],
  },
  {
    id: 'web_monitoring',
    name: 'Web Monitoring',
    version: '0.1.0',
    description: 'HTTP/S scenario health, response times, SSL/TLS, and URL availability',
    enabled: true,
    route: '/web-monitoring',
    navItem: { label: 'Web Monitoring', path: '/web-monitoring', order: 11 },
    permissions: ['module.web_monitoring.view'],
  },
  {
    id: 'services',
    name: 'Services',
    version: '0.1.0',
    description: 'Business and technical service dependency tree and SLA tracking',
    enabled: true,
    route: '/services',
    navItem: { label: 'Services', path: '/services', order: 12 },
    permissions: ['module.services.view'],
  },
  {
    id: 'applications',
    name: 'Applications',
    version: '0.1.0',
    description: 'Application health, middleware metrics, and service relationships',
    enabled: true,
    route: '/applications',
    navItem: { label: 'Applications', path: '/applications', order: 13 },
    permissions: ['module.applications.view'],
  },
  {
    id: 'capacity',
    name: 'Capacity Planning',
    version: '0.1.0',
    description: 'Resource growth forecasting, threshold tracking, and exhaustion estimation',
    enabled: true,
    route: '/capacity',
    navItem: { label: 'Capacity', path: '/capacity', order: 14 },
    permissions: ['module.capacity.view'],
  },
  {
    id: 'trend_detection',
    name: 'Trend Detection',
    version: '0.1.0',
    description: 'Sustained degradation, baseline comparison, and anomaly candidate identification',
    enabled: true,
    route: '/trends',
    navItem: { label: 'Trend Detection', path: '/trends', order: 15 },
    permissions: ['module.trend_detection.view'],
  },
  {
    id: 'infra_map',
    name: 'Infrastructure Map',
    version: '0.1.0',
    description: 'Visual topological relationships, dependencies, and incident overlays',
    enabled: true,
    route: '/infra-map',
    navItem: { label: 'Topology Map', path: '/infra-map', order: 16 },
    permissions: ['module.infra_map.view'],
  },
  {
    id: 'dashboards',
    name: 'Dashboard Builder',
    version: '0.1.0',
    description: 'Configurable custom operational dashboards and NOC wall layouts',
    enabled: true,
    route: '/dashboards',
    navItem: { label: 'Dashboards', path: '/dashboards', order: 17 },
    permissions: ['module.dashboards.view'],
  },
  {
    id: 'reports',
    name: 'Reports',
    version: '0.1.0',
    description: 'Scheduled and on-demand PDF/CSV availability, SLA, and capacity reports',
    enabled: true,
    route: '/reports',
    navItem: { label: 'Reports', path: '/reports', order: 18 },
    permissions: ['module.reports.view'],
  },
  {
    id: 'alert_analytics',
    name: 'Alert Analytics',
    version: '0.1.0',
    description: 'MTTR, MTBF, alert volume distribution, and noisy trigger analysis',
    enabled: true,
    route: '/alert-analytics',
    navItem: { label: 'Alert Analytics', path: '/alert-analytics', order: 19 },
    permissions: ['module.alert_analytics.view'],
  },
  {
    id: 'noc_wall',
    name: 'NOC Wall',
    version: '0.1.0',
    description: 'Fullscreen rotating operations wallboard for 24/7 monitoring centers',
    enabled: true,
    route: '/noc-wall',
    navItem: { label: 'NOC Wall', path: '/noc-wall', order: 20 },
    permissions: ['module.noc_wall.view'],
  },
  {
    id: 'intelligence',
    name: 'AI & Intelligence',
    version: '0.1.0',
    description: 'Future operational assistant, incident summarization, and root-cause candidate analysis',
    enabled: true,
    route: '/intelligence',
    navItem: { label: 'AI Intelligence', path: '/intelligence', order: 21 },
    permissions: ['module.intelligence.view'],
  },
];

// Register all modules into the frontend registry
moduleDefinitions.forEach((mod) => moduleRegistry.register(mod));

export { moduleRegistry };
export * from './types';
export * from './registry';
